---
- name: Ensure flatpak is installed
  ansible.builtin.dnf:
    name: flatpak
    state: present
  become: true

# --- REPOSITORY SETUP ---

- name: Add the Flathub repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    method: system
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  become: true

- name: Add the Fedora Flatpak repository
  community.general.flatpak_remote:
    name: fedora
    state: present
    method: system
    flatpakrepo_url: oci+https://registry.fedoraproject.org
  become: true

# --- INSTALLATION SECTIONS ---

- name: Install packages from Flathub
  community.general.flatpak:
    name: "{{ workstation_flatpaks_flathub }}"
    state: present
    method: system
    remote: flathub
  become: true

- name: Install packages from Fedora Repo
  community.general.flatpak:
    name: "{{ workstation_flatpaks_fedora }}"
    state: present
    method: system
    remote: fedora
  become: true