---
- name: Create a symlink for snapd
  ansible.builtin.file:
    src: "/var/lib/snapd/snap"
    dest: "/snap"
    state: link
  become: true

- name: Install Snap packages (Standard)
  community.general.snap:
    name: "{{ workstation_snaps_standard }}"
    state: present
  become: true

- name: Install Snap packages with --classic flag
  community.general.snap:
    classic: true
    name: "{{ workstation_snaps_classic }}"
    state: present
  become: true
