---
- name: Ensure required administrative groups exist
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - wheel
    - libvirt
    - video
    - render

- name: Provision workstation administrator user
  ansible.builtin.user:
    name: "{{ workstation_admin_user }}"
    state: present
    groups: 'wheel,libvirt,incus-admin,lxd,video,render'
    append: true
    create_home: true
    shell: /bin/bash
    password: "{{ workstation_admin_password | sha512_hash if (workstation_admin_password | length > 0) else omit }}"
  become: true
  no_log: true
  when: workstation_admin_user | length > 0

- name: Provision standard workstation user
  ansible.builtin.user:
    name: "{{ workstation_standard_user }}"
    state: present
    groups: 'libvirt,incus,video,render'
    append: true
    create_home: true
    shell: /bin/bash
    password: "{{ workstation_standard_password | sha512_hash if (workstation_standard_password | length > 0) else omit }}"
  become: true
  no_log: true
  when: workstation_standard_user | length > 0

- name: Ensure guest user exists with restricted access
  ansible.builtin.user:
    name: guest
    state: present
    groups: ''
    append: false
    create_home: true
    shell: /bin/bash
  become: true
